//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryServiceInfoReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tContinent : object
    {
        
        private string sCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCurrency : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndName", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndName : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndNameGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndNameGroupedByContinent : object
    {
        
        private CountryServiceInfoReference.tContinent ContinentField;
        
        private CountryServiceInfoReference.tCountryCodeAndName[] CountryCodeAndNamesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public CountryServiceInfoReference.tContinent Continent
        {
            get
            {
                return this.ContinentField;
            }
            set
            {
                this.ContinentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public CountryServiceInfoReference.tCountryCodeAndName[] CountryCodeAndNames
        {
            get
            {
                return this.CountryCodeAndNamesField;
            }
            set
            {
                this.CountryCodeAndNamesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryInfo : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        private string sCapitalCityField;
        
        private string sPhoneCodeField;
        
        private string sContinentCodeField;
        
        private string sCurrencyISOCodeField;
        
        private string sCountryFlagField;
        
        private CountryServiceInfoReference.tLanguage[] LanguagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string sCapitalCity
        {
            get
            {
                return this.sCapitalCityField;
            }
            set
            {
                this.sCapitalCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string sPhoneCode
        {
            get
            {
                return this.sPhoneCodeField;
            }
            set
            {
                this.sPhoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string sContinentCode
        {
            get
            {
                return this.sContinentCodeField;
            }
            set
            {
                this.sContinentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string sCurrencyISOCode
        {
            get
            {
                return this.sCurrencyISOCodeField;
            }
            set
            {
                this.sCurrencyISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string sCountryFlag
        {
            get
            {
                return this.sCountryFlagField;
            }
            set
            {
                this.sCountryFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public CountryServiceInfoReference.tLanguage[] Languages
        {
            get
            {
                return this.LanguagesField;
            }
            set
            {
                this.LanguagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLanguage", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tLanguage : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo", ConfigurationName="CountryServiceInfoReference.CountryInfoServiceSoapType")]
    public interface CountryInfoServiceSoapType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfContinentsByNameResponse> ListOfContinentsByNameAsync(CountryServiceInfoReference.ListOfContinentsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfContinentsByCodeResponse> ListOfContinentsByCodeAsync(CountryServiceInfoReference.ListOfContinentsByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCurrenciesByNameResponse> ListOfCurrenciesByNameAsync(CountryServiceInfoReference.ListOfCurrenciesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCurrenciesByCodeResponse> ListOfCurrenciesByCodeAsync(CountryServiceInfoReference.ListOfCurrenciesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CurrencyNameResponse> CurrencyNameAsync(CountryServiceInfoReference.CurrencyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCountryNamesByCodeResponse> ListOfCountryNamesByCodeAsync(CountryServiceInfoReference.ListOfCountryNamesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCountryNamesByNameResponse> ListOfCountryNamesByNameAsync(CountryServiceInfoReference.ListOfCountryNamesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentResponse> ListOfCountryNamesGroupedByContinentAsync(CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CountryNameResponse> CountryNameAsync(CountryServiceInfoReference.CountryNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CountryISOCodeResponse> CountryISOCodeAsync(CountryServiceInfoReference.CountryISOCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CapitalCityResponse> CapitalCityAsync(CountryServiceInfoReference.CapitalCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CountryCurrencyResponse> CountryCurrencyAsync(CountryServiceInfoReference.CountryCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CountryFlagResponse> CountryFlagAsync(CountryServiceInfoReference.CountryFlagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CountryIntPhoneCodeResponse> CountryIntPhoneCodeAsync(CountryServiceInfoReference.CountryIntPhoneCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.FullCountryInfoResponse> FullCountryInfoAsync(CountryServiceInfoReference.FullCountryInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.FullCountryInfoAllCountriesResponse> FullCountryInfoAllCountriesAsync(CountryServiceInfoReference.FullCountryInfoAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.CountriesUsingCurrencyResponse> CountriesUsingCurrencyAsync(CountryServiceInfoReference.CountriesUsingCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfLanguagesByNameResponse> ListOfLanguagesByNameAsync(CountryServiceInfoReference.ListOfLanguagesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfLanguagesByCodeResponse> ListOfLanguagesByCodeAsync(CountryServiceInfoReference.ListOfLanguagesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.LanguageNameResponse> LanguageNameAsync(CountryServiceInfoReference.LanguageNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CountryServiceInfoReference.LanguageISOCodeResponse> LanguageISOCodeAsync(CountryServiceInfoReference.LanguageISOCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfContinentsByNameRequestBody Body;
        
        public ListOfContinentsByNameRequest()
        {
        }
        
        public ListOfContinentsByNameRequest(CountryServiceInfoReference.ListOfContinentsByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfContinentsByNameRequestBody
    {
        
        public ListOfContinentsByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfContinentsByNameResponseBody Body;
        
        public ListOfContinentsByNameResponse()
        {
        }
        
        public ListOfContinentsByNameResponse(CountryServiceInfoReference.ListOfContinentsByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfContinentsByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tContinent[] ListOfContinentsByNameResult;
        
        public ListOfContinentsByNameResponseBody()
        {
        }
        
        public ListOfContinentsByNameResponseBody(CountryServiceInfoReference.tContinent[] ListOfContinentsByNameResult)
        {
            this.ListOfContinentsByNameResult = ListOfContinentsByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfContinentsByCodeRequestBody Body;
        
        public ListOfContinentsByCodeRequest()
        {
        }
        
        public ListOfContinentsByCodeRequest(CountryServiceInfoReference.ListOfContinentsByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfContinentsByCodeRequestBody
    {
        
        public ListOfContinentsByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfContinentsByCodeResponseBody Body;
        
        public ListOfContinentsByCodeResponse()
        {
        }
        
        public ListOfContinentsByCodeResponse(CountryServiceInfoReference.ListOfContinentsByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfContinentsByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tContinent[] ListOfContinentsByCodeResult;
        
        public ListOfContinentsByCodeResponseBody()
        {
        }
        
        public ListOfContinentsByCodeResponseBody(CountryServiceInfoReference.tContinent[] ListOfContinentsByCodeResult)
        {
            this.ListOfContinentsByCodeResult = ListOfContinentsByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCurrenciesByNameRequestBody Body;
        
        public ListOfCurrenciesByNameRequest()
        {
        }
        
        public ListOfCurrenciesByNameRequest(CountryServiceInfoReference.ListOfCurrenciesByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCurrenciesByNameRequestBody
    {
        
        public ListOfCurrenciesByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCurrenciesByNameResponseBody Body;
        
        public ListOfCurrenciesByNameResponse()
        {
        }
        
        public ListOfCurrenciesByNameResponse(CountryServiceInfoReference.ListOfCurrenciesByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCurrenciesByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCurrency[] ListOfCurrenciesByNameResult;
        
        public ListOfCurrenciesByNameResponseBody()
        {
        }
        
        public ListOfCurrenciesByNameResponseBody(CountryServiceInfoReference.tCurrency[] ListOfCurrenciesByNameResult)
        {
            this.ListOfCurrenciesByNameResult = ListOfCurrenciesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCurrenciesByCodeRequestBody Body;
        
        public ListOfCurrenciesByCodeRequest()
        {
        }
        
        public ListOfCurrenciesByCodeRequest(CountryServiceInfoReference.ListOfCurrenciesByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCurrenciesByCodeRequestBody
    {
        
        public ListOfCurrenciesByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCurrenciesByCodeResponseBody Body;
        
        public ListOfCurrenciesByCodeResponse()
        {
        }
        
        public ListOfCurrenciesByCodeResponse(CountryServiceInfoReference.ListOfCurrenciesByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCurrenciesByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCurrency[] ListOfCurrenciesByCodeResult;
        
        public ListOfCurrenciesByCodeResponseBody()
        {
        }
        
        public ListOfCurrenciesByCodeResponseBody(CountryServiceInfoReference.tCurrency[] ListOfCurrenciesByCodeResult)
        {
            this.ListOfCurrenciesByCodeResult = ListOfCurrenciesByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CurrencyNameRequestBody Body;
        
        public CurrencyNameRequest()
        {
        }
        
        public CurrencyNameRequest(CountryServiceInfoReference.CurrencyNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CurrencyNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCurrencyISOCode;
        
        public CurrencyNameRequestBody()
        {
        }
        
        public CurrencyNameRequestBody(string sCurrencyISOCode)
        {
            this.sCurrencyISOCode = sCurrencyISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CurrencyNameResponseBody Body;
        
        public CurrencyNameResponse()
        {
        }
        
        public CurrencyNameResponse(CountryServiceInfoReference.CurrencyNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CurrencyNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrencyNameResult;
        
        public CurrencyNameResponseBody()
        {
        }
        
        public CurrencyNameResponseBody(string CurrencyNameResult)
        {
            this.CurrencyNameResult = CurrencyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCountryNamesByCodeRequestBody Body;
        
        public ListOfCountryNamesByCodeRequest()
        {
        }
        
        public ListOfCountryNamesByCodeRequest(CountryServiceInfoReference.ListOfCountryNamesByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCountryNamesByCodeRequestBody
    {
        
        public ListOfCountryNamesByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCountryNamesByCodeResponseBody Body;
        
        public ListOfCountryNamesByCodeResponse()
        {
        }
        
        public ListOfCountryNamesByCodeResponse(CountryServiceInfoReference.ListOfCountryNamesByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCountryNamesByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCountryCodeAndName[] ListOfCountryNamesByCodeResult;
        
        public ListOfCountryNamesByCodeResponseBody()
        {
        }
        
        public ListOfCountryNamesByCodeResponseBody(CountryServiceInfoReference.tCountryCodeAndName[] ListOfCountryNamesByCodeResult)
        {
            this.ListOfCountryNamesByCodeResult = ListOfCountryNamesByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCountryNamesByNameRequestBody Body;
        
        public ListOfCountryNamesByNameRequest()
        {
        }
        
        public ListOfCountryNamesByNameRequest(CountryServiceInfoReference.ListOfCountryNamesByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCountryNamesByNameRequestBody
    {
        
        public ListOfCountryNamesByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCountryNamesByNameResponseBody Body;
        
        public ListOfCountryNamesByNameResponse()
        {
        }
        
        public ListOfCountryNamesByNameResponse(CountryServiceInfoReference.ListOfCountryNamesByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCountryNamesByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCountryCodeAndName[] ListOfCountryNamesByNameResult;
        
        public ListOfCountryNamesByNameResponseBody()
        {
        }
        
        public ListOfCountryNamesByNameResponseBody(CountryServiceInfoReference.tCountryCodeAndName[] ListOfCountryNamesByNameResult)
        {
            this.ListOfCountryNamesByNameResult = ListOfCountryNamesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesGroupedByContinentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentRequestBody Body;
        
        public ListOfCountryNamesGroupedByContinentRequest()
        {
        }
        
        public ListOfCountryNamesGroupedByContinentRequest(CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCountryNamesGroupedByContinentRequestBody
    {
        
        public ListOfCountryNamesGroupedByContinentRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesGroupedByContinentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinentResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentResponseBody Body;
        
        public ListOfCountryNamesGroupedByContinentResponse()
        {
        }
        
        public ListOfCountryNamesGroupedByContinentResponse(CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCountryNamesGroupedByContinentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult;
        
        public ListOfCountryNamesGroupedByContinentResponseBody()
        {
        }
        
        public ListOfCountryNamesGroupedByContinentResponseBody(CountryServiceInfoReference.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult)
        {
            this.ListOfCountryNamesGroupedByContinentResult = ListOfCountryNamesGroupedByContinentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryNameRequestBody Body;
        
        public CountryNameRequest()
        {
        }
        
        public CountryNameRequest(CountryServiceInfoReference.CountryNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryNameRequestBody()
        {
        }
        
        public CountryNameRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryNameResponseBody Body;
        
        public CountryNameResponse()
        {
        }
        
        public CountryNameResponse(CountryServiceInfoReference.CountryNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryNameResult;
        
        public CountryNameResponseBody()
        {
        }
        
        public CountryNameResponseBody(string CountryNameResult)
        {
            this.CountryNameResult = CountryNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryISOCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryISOCodeRequestBody Body;
        
        public CountryISOCodeRequest()
        {
        }
        
        public CountryISOCodeRequest(CountryServiceInfoReference.CountryISOCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryISOCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryName;
        
        public CountryISOCodeRequestBody()
        {
        }
        
        public CountryISOCodeRequestBody(string sCountryName)
        {
            this.sCountryName = sCountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryISOCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryISOCodeResponseBody Body;
        
        public CountryISOCodeResponse()
        {
        }
        
        public CountryISOCodeResponse(CountryServiceInfoReference.CountryISOCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryISOCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryISOCodeResult;
        
        public CountryISOCodeResponseBody()
        {
        }
        
        public CountryISOCodeResponseBody(string CountryISOCodeResult)
        {
            this.CountryISOCodeResult = CountryISOCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapitalCityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCity", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CapitalCityRequestBody Body;
        
        public CapitalCityRequest()
        {
        }
        
        public CapitalCityRequest(CountryServiceInfoReference.CapitalCityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CapitalCityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CapitalCityRequestBody()
        {
        }
        
        public CapitalCityRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapitalCityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCityResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CapitalCityResponseBody Body;
        
        public CapitalCityResponse()
        {
        }
        
        public CapitalCityResponse(CountryServiceInfoReference.CapitalCityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CapitalCityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CapitalCityResult;
        
        public CapitalCityResponseBody()
        {
        }
        
        public CapitalCityResponseBody(string CapitalCityResult)
        {
            this.CapitalCityResult = CapitalCityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryCurrencyRequestBody Body;
        
        public CountryCurrencyRequest()
        {
        }
        
        public CountryCurrencyRequest(CountryServiceInfoReference.CountryCurrencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryCurrencyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryCurrencyRequestBody()
        {
        }
        
        public CountryCurrencyRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryCurrencyResponseBody Body;
        
        public CountryCurrencyResponse()
        {
        }
        
        public CountryCurrencyResponse(CountryServiceInfoReference.CountryCurrencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryCurrencyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCurrency CountryCurrencyResult;
        
        public CountryCurrencyResponseBody()
        {
        }
        
        public CountryCurrencyResponseBody(CountryServiceInfoReference.tCurrency CountryCurrencyResult)
        {
            this.CountryCurrencyResult = CountryCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryFlagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlag", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryFlagRequestBody Body;
        
        public CountryFlagRequest()
        {
        }
        
        public CountryFlagRequest(CountryServiceInfoReference.CountryFlagRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryFlagRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryFlagRequestBody()
        {
        }
        
        public CountryFlagRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryFlagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlagResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryFlagResponseBody Body;
        
        public CountryFlagResponse()
        {
        }
        
        public CountryFlagResponse(CountryServiceInfoReference.CountryFlagResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryFlagResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryFlagResult;
        
        public CountryFlagResponseBody()
        {
        }
        
        public CountryFlagResponseBody(string CountryFlagResult)
        {
            this.CountryFlagResult = CountryFlagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryIntPhoneCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryIntPhoneCodeRequestBody Body;
        
        public CountryIntPhoneCodeRequest()
        {
        }
        
        public CountryIntPhoneCodeRequest(CountryServiceInfoReference.CountryIntPhoneCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryIntPhoneCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryIntPhoneCodeRequestBody()
        {
        }
        
        public CountryIntPhoneCodeRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryIntPhoneCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountryIntPhoneCodeResponseBody Body;
        
        public CountryIntPhoneCodeResponse()
        {
        }
        
        public CountryIntPhoneCodeResponse(CountryServiceInfoReference.CountryIntPhoneCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryIntPhoneCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryIntPhoneCodeResult;
        
        public CountryIntPhoneCodeResponseBody()
        {
        }
        
        public CountryIntPhoneCodeResponseBody(string CountryIntPhoneCodeResult)
        {
            this.CountryIntPhoneCodeResult = CountryIntPhoneCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.FullCountryInfoRequestBody Body;
        
        public FullCountryInfoRequest()
        {
        }
        
        public FullCountryInfoRequest(CountryServiceInfoReference.FullCountryInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class FullCountryInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public FullCountryInfoRequestBody()
        {
        }
        
        public FullCountryInfoRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.FullCountryInfoResponseBody Body;
        
        public FullCountryInfoResponse()
        {
        }
        
        public FullCountryInfoResponse(CountryServiceInfoReference.FullCountryInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class FullCountryInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCountryInfo FullCountryInfoResult;
        
        public FullCountryInfoResponseBody()
        {
        }
        
        public FullCountryInfoResponseBody(CountryServiceInfoReference.tCountryInfo FullCountryInfoResult)
        {
            this.FullCountryInfoResult = FullCountryInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoAllCountriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountries", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.FullCountryInfoAllCountriesRequestBody Body;
        
        public FullCountryInfoAllCountriesRequest()
        {
        }
        
        public FullCountryInfoAllCountriesRequest(CountryServiceInfoReference.FullCountryInfoAllCountriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FullCountryInfoAllCountriesRequestBody
    {
        
        public FullCountryInfoAllCountriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoAllCountriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountriesResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.FullCountryInfoAllCountriesResponseBody Body;
        
        public FullCountryInfoAllCountriesResponse()
        {
        }
        
        public FullCountryInfoAllCountriesResponse(CountryServiceInfoReference.FullCountryInfoAllCountriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class FullCountryInfoAllCountriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCountryInfo[] FullCountryInfoAllCountriesResult;
        
        public FullCountryInfoAllCountriesResponseBody()
        {
        }
        
        public FullCountryInfoAllCountriesResponseBody(CountryServiceInfoReference.tCountryInfo[] FullCountryInfoAllCountriesResult)
        {
            this.FullCountryInfoAllCountriesResult = FullCountryInfoAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountriesUsingCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountriesUsingCurrencyRequestBody Body;
        
        public CountriesUsingCurrencyRequest()
        {
        }
        
        public CountriesUsingCurrencyRequest(CountryServiceInfoReference.CountriesUsingCurrencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountriesUsingCurrencyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sISOCurrencyCode;
        
        public CountriesUsingCurrencyRequestBody()
        {
        }
        
        public CountriesUsingCurrencyRequestBody(string sISOCurrencyCode)
        {
            this.sISOCurrencyCode = sISOCurrencyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountriesUsingCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.CountriesUsingCurrencyResponseBody Body;
        
        public CountriesUsingCurrencyResponse()
        {
        }
        
        public CountriesUsingCurrencyResponse(CountryServiceInfoReference.CountriesUsingCurrencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountriesUsingCurrencyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tCountryCodeAndName[] CountriesUsingCurrencyResult;
        
        public CountriesUsingCurrencyResponseBody()
        {
        }
        
        public CountriesUsingCurrencyResponseBody(CountryServiceInfoReference.tCountryCodeAndName[] CountriesUsingCurrencyResult)
        {
            this.CountriesUsingCurrencyResult = CountriesUsingCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfLanguagesByNameRequestBody Body;
        
        public ListOfLanguagesByNameRequest()
        {
        }
        
        public ListOfLanguagesByNameRequest(CountryServiceInfoReference.ListOfLanguagesByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfLanguagesByNameRequestBody
    {
        
        public ListOfLanguagesByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfLanguagesByNameResponseBody Body;
        
        public ListOfLanguagesByNameResponse()
        {
        }
        
        public ListOfLanguagesByNameResponse(CountryServiceInfoReference.ListOfLanguagesByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfLanguagesByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tLanguage[] ListOfLanguagesByNameResult;
        
        public ListOfLanguagesByNameResponseBody()
        {
        }
        
        public ListOfLanguagesByNameResponseBody(CountryServiceInfoReference.tLanguage[] ListOfLanguagesByNameResult)
        {
            this.ListOfLanguagesByNameResult = ListOfLanguagesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfLanguagesByCodeRequestBody Body;
        
        public ListOfLanguagesByCodeRequest()
        {
        }
        
        public ListOfLanguagesByCodeRequest(CountryServiceInfoReference.ListOfLanguagesByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfLanguagesByCodeRequestBody
    {
        
        public ListOfLanguagesByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.ListOfLanguagesByCodeResponseBody Body;
        
        public ListOfLanguagesByCodeResponse()
        {
        }
        
        public ListOfLanguagesByCodeResponse(CountryServiceInfoReference.ListOfLanguagesByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfLanguagesByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CountryServiceInfoReference.tLanguage[] ListOfLanguagesByCodeResult;
        
        public ListOfLanguagesByCodeResponseBody()
        {
        }
        
        public ListOfLanguagesByCodeResponseBody(CountryServiceInfoReference.tLanguage[] ListOfLanguagesByCodeResult)
        {
            this.ListOfLanguagesByCodeResult = ListOfLanguagesByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.LanguageNameRequestBody Body;
        
        public LanguageNameRequest()
        {
        }
        
        public LanguageNameRequest(CountryServiceInfoReference.LanguageNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sISOCode;
        
        public LanguageNameRequestBody()
        {
        }
        
        public LanguageNameRequestBody(string sISOCode)
        {
            this.sISOCode = sISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.LanguageNameResponseBody Body;
        
        public LanguageNameResponse()
        {
        }
        
        public LanguageNameResponse(CountryServiceInfoReference.LanguageNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LanguageNameResult;
        
        public LanguageNameResponseBody()
        {
        }
        
        public LanguageNameResponseBody(string LanguageNameResult)
        {
            this.LanguageNameResult = LanguageNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageISOCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.LanguageISOCodeRequestBody Body;
        
        public LanguageISOCodeRequest()
        {
        }
        
        public LanguageISOCodeRequest(CountryServiceInfoReference.LanguageISOCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageISOCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLanguageName;
        
        public LanguageISOCodeRequestBody()
        {
        }
        
        public LanguageISOCodeRequestBody(string sLanguageName)
        {
            this.sLanguageName = sLanguageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageISOCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public CountryServiceInfoReference.LanguageISOCodeResponseBody Body;
        
        public LanguageISOCodeResponse()
        {
        }
        
        public LanguageISOCodeResponse(CountryServiceInfoReference.LanguageISOCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageISOCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LanguageISOCodeResult;
        
        public LanguageISOCodeResponseBody()
        {
        }
        
        public LanguageISOCodeResponseBody(string LanguageISOCodeResult)
        {
            this.LanguageISOCodeResult = LanguageISOCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CountryInfoServiceSoapTypeChannel : CountryServiceInfoReference.CountryInfoServiceSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CountryInfoServiceSoapTypeClient : System.ServiceModel.ClientBase<CountryServiceInfoReference.CountryInfoServiceSoapType>, CountryServiceInfoReference.CountryInfoServiceSoapType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), CountryInfoServiceSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfContinentsByNameResponse> ListOfContinentsByNameAsync(CountryServiceInfoReference.ListOfContinentsByNameRequest request)
        {
            return base.Channel.ListOfContinentsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfContinentsByCodeResponse> ListOfContinentsByCodeAsync(CountryServiceInfoReference.ListOfContinentsByCodeRequest request)
        {
            return base.Channel.ListOfContinentsByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCurrenciesByNameResponse> ListOfCurrenciesByNameAsync(CountryServiceInfoReference.ListOfCurrenciesByNameRequest request)
        {
            return base.Channel.ListOfCurrenciesByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCurrenciesByCodeResponse> ListOfCurrenciesByCodeAsync(CountryServiceInfoReference.ListOfCurrenciesByCodeRequest request)
        {
            return base.Channel.ListOfCurrenciesByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CurrencyNameResponse> CurrencyNameAsync(CountryServiceInfoReference.CurrencyNameRequest request)
        {
            return base.Channel.CurrencyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCountryNamesByCodeResponse> ListOfCountryNamesByCodeAsync(CountryServiceInfoReference.ListOfCountryNamesByCodeRequest request)
        {
            return base.Channel.ListOfCountryNamesByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCountryNamesByNameResponse> ListOfCountryNamesByNameAsync(CountryServiceInfoReference.ListOfCountryNamesByNameRequest request)
        {
            return base.Channel.ListOfCountryNamesByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentResponse> ListOfCountryNamesGroupedByContinentAsync(CountryServiceInfoReference.ListOfCountryNamesGroupedByContinentRequest request)
        {
            return base.Channel.ListOfCountryNamesGroupedByContinentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CountryNameResponse> CountryNameAsync(CountryServiceInfoReference.CountryNameRequest request)
        {
            return base.Channel.CountryNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CountryISOCodeResponse> CountryISOCodeAsync(CountryServiceInfoReference.CountryISOCodeRequest request)
        {
            return base.Channel.CountryISOCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CapitalCityResponse> CapitalCityAsync(CountryServiceInfoReference.CapitalCityRequest request)
        {
            return base.Channel.CapitalCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CountryCurrencyResponse> CountryCurrencyAsync(CountryServiceInfoReference.CountryCurrencyRequest request)
        {
            return base.Channel.CountryCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CountryFlagResponse> CountryFlagAsync(CountryServiceInfoReference.CountryFlagRequest request)
        {
            return base.Channel.CountryFlagAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CountryIntPhoneCodeResponse> CountryIntPhoneCodeAsync(CountryServiceInfoReference.CountryIntPhoneCodeRequest request)
        {
            return base.Channel.CountryIntPhoneCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.FullCountryInfoResponse> FullCountryInfoAsync(CountryServiceInfoReference.FullCountryInfoRequest request)
        {
            return base.Channel.FullCountryInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.FullCountryInfoAllCountriesResponse> FullCountryInfoAllCountriesAsync(CountryServiceInfoReference.FullCountryInfoAllCountriesRequest request)
        {
            return base.Channel.FullCountryInfoAllCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.CountriesUsingCurrencyResponse> CountriesUsingCurrencyAsync(CountryServiceInfoReference.CountriesUsingCurrencyRequest request)
        {
            return base.Channel.CountriesUsingCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfLanguagesByNameResponse> ListOfLanguagesByNameAsync(CountryServiceInfoReference.ListOfLanguagesByNameRequest request)
        {
            return base.Channel.ListOfLanguagesByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.ListOfLanguagesByCodeResponse> ListOfLanguagesByCodeAsync(CountryServiceInfoReference.ListOfLanguagesByCodeRequest request)
        {
            return base.Channel.ListOfLanguagesByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.LanguageNameResponse> LanguageNameAsync(CountryServiceInfoReference.LanguageNameRequest request)
        {
            return base.Channel.LanguageNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CountryServiceInfoReference.LanguageISOCodeResponse> LanguageISOCodeAsync(CountryServiceInfoReference.LanguageISOCodeRequest request)
        {
            return base.Channel.LanguageISOCodeAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CountryInfoServiceSoap,
            
            CountryInfoServiceSoap12,
        }
    }
}
